### ISSUE TITLE
unrecognized opcode `fence.i', extension `zifencei' required

### ISSUE THREAD

**Issue by wwwuxy** [artecs-group/PERCIVAL#7]
when i run `./ci/install-riscvpk.sh`, I get this error,my way is add `CFLAGS += -march=rv64imafdc_zifencei` in riscv-pk/build/makefile, then follow install-riscvpk.sh, now the problem has been solved~
![Snipaste_2024-11-09_09-52-14](https://github.com/user-attachments/assets/b42649e7-2687-4c6a-9cb6-8aa1ff2ab80e)

**Comment by davidmallasen** [comment]
Thanks for reporting this. We'll add it to the README with the updated instructions @MarioInf-UCM

**Comment by davidmallasen** [comment]
Fixed in #8
